# Setup
title:               bsdgox
tagline:             'C++'
description:         ''
url:                 https://cpplang.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Goran Aranđelović
  url:               https://goranarandjelovic.com
  email:             goran.arandjelovic@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
